### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oliland** [uclcg/uclcg#4]
Would it be possible to attach a license to this code?

Other libraries likely exist for managing WebGL deployments - but I have the benefit of being already familiar with this one :) it would be a great starting point for some interactive demonstrations that I'd like to host on my own website and potentially with future collaborators.

Thanks for all the hard work you put into this!

**Comment by oliland** [comment]
Paging maybe @mfischer-ucl or @henzler?

**Comment by uclcg** [comment]
discussed offline, closing this. -mf
